---
on:
  push:
    branches-ignore:
      - "gh-pages"
  pull_request:

name: format

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua
